### ISSUE TITLE
你好，可以把下载字幕的路径设置为跟视频同一路径吗？

### ISSUE THREAD

**Issue by zasl** [lxalxy/SubtitleDownload#1]
这是我唯一一个在路由器上能运行的python字幕下载工具，不过下载的字幕是和py脚本同目录，在路由器上操作很麻烦。而且是否可以支持整个目录搜索视频下载？

**Comment by mzbhy** [comment]
你好，十分抱歉，很久没有上GITHUB了，之前我没有在Linux下测试过。我已经修正了你说的问题，并且支持了目录搜索下载。
